import { defineField, defineType } from "sanity";
import { User } from "lucide-react";

export default defineType({
    name: "userAccount",
    title: "Счет пользователя",
    type: "document",
    icon: User,
    groups: [
        {
            name: "user",
            title: "Пользователь",
            default: true,
        },
        {
            name: "donations",
            title: "Пожертвования",
        },
        {
            name: "auth",
            title: "Аутентификация",
        },
        {
            name: "preferences",
            title: "Предпочтения",
        },
        {
            name: "amo",
            title: "AmoCRM",
        },
        {
            name: "meta",
            title: "Мета данные",
        },
    ],
    fields: [
        defineField({
            name: "name",
            title: "Имя пользователя",
            type: "string",
            description: "Полное имя пользователя",
            validation: (Rule) => Rule.required().warning("Имя пользователя обязательно"),
            group: "user",
        }),
        defineField({
            name: "phone",
            title: "Телефон",
            type: "string",
            description: "Номер телефона пользователя в международном формате (например, +7XXXXXXXXXX)",
            validation: (Rule) => Rule.required().warning("Телефон обязателен"),
            group: "user",
        }),
        defineField({
            name: "email",
            title: "Email",
            type: "string",
            description: "Уникальный email для входа",
            validation: (Rule) => Rule.required().email().error("Укажите корректный email"),
            group: "auth",
        }),
        defineField({
            name: "password",
            title: "Хэш пароля",
            type: "string",
            description: "Хэшированный пароль пользователя (только сервер)",
            group: "auth",
        }),
        defineField({
            name: "date",
            title: "Дата мероприятия",
            type: "datetime",
            description: "Дата планируемого мероприятия",
            group: "user",
        }),
        defineField({
            name: "userDonationLink",
            title: "Ссылка на пополнение счета пользователя",
            type: "string",
            description: "Ссылка на пополнение счета пользователя",
            group: "donations",
        }),
        defineField({
            name: "userId",
            title: "ID пользователя",
            type: "string",
            description: "Уникальный идентификатор пользователя",
            validation: (Rule) => Rule.required().warning("ID пользователя обязателен"),
            group: "meta",
        }),
        defineField({
            name: "region",
            title: "Регион",
            type: "string",
            description: "Регион пользователя (например, Москва, Санкт-Петербург)",
            validation: (Rule) => Rule.required().warning("Регион обязателен"),
            group: "user",
        }),
        defineField({
            name: "referralId",
            title: "Referral ID",
            type: "string",
            description: "Уникальный UUID для реферальной ссылки",
            group: "auth",
        }),
        defineField({
            name: "referralLink",
            title: "Реферальная ссылка",
            type: "string",
            description: "Сгенерированная реферальная ссылка для пользователя",
            group: "auth",
        }),
        defineField({
            name: "privacyPolicy",
            title: "Согласие на обработку персональных данных",
            type: "boolean",
            description: "Согласие на обработку персональных данных пользователя",
            group: "meta",
        }),
        defineField({
            name: "totalAmount",
            title: "Сумма перечисленных денег",
            type: "number",
            description: "Сумма денег, перечисленных на этот счёт (RUB)",
            validation: (Rule) => Rule.required().precision(2),
            initialValue: 0,
            group: "donations",
        }),
        defineField({
            name: "accountSum",
            title: "Сумма подписки",
            type: "number",
            description: "Размер регулярного платежа (по умолчанию 4000)",
            initialValue: 4000,
            group: "preferences",
        }),
        defineField({
            name: "isActive",
            title: "Статус аккаунта",
            type: "boolean",
            description: "Активен ли аккаунт",
            initialValue: true,
            group: "meta",
        }),
        defineField({
            name: "lastLoginAt",
            title: "Последний вход",
            type: "datetime",
            description: "Последнее время входа пользователя",
            group: "auth",
        }),
        // Предпочтения букета и доставки
        defineField({
            name: "bouquetCategory",
            title: "Категория букета",
            type: "string",
            description: "Предпочитаемая категория букетов",
            group: "preferences",
        }),
        defineField({
            name: "deliveryAddress",
            title: "Адрес доставки",
            type: "string",
            description: "Адрес доставки букетов",
            group: "preferences",
        }),
        defineField({
            name: "deliveryDate",
            title: "Дата первой доставки",
            type: "datetime",
            description: "Дата планируемой доставки",
            group: "preferences",
        }),
        defineField({
            name: "deliveryInterval",
            title: "Интервал доставки",
            type: "string",
            description: "Как часто доставлять (еженедельно/ежемесячно и т.д.)",
            group: "preferences",
        }),
        defineField({
            name: "bouquetWishes",
            title: "Пожелания к букету",
            type: "text",
            description: "Пожелания пользователя",
            group: "preferences",
        }),
        // AmoCRM IDs
        defineField({
            name: "amoLeadId",
            title: "AmoCRM Lead ID",
            type: "string",
            description: "Идентификатор лида в AmoCRM",
            group: "amo",
        }),
        defineField({
            name: "amoContactId",
            title: "AmoCRM Contact ID",
            type: "string",
            description: "Идентификатор контакта в AmoCRM",
            group: "amo",
        }),
        // Поля для восстановления пароля
        defineField({
            name: "resetToken",
            title: "Токен сброса пароля",
            type: "string",
            description: "Токен для восстановления пароля",
            group: "auth",
        }),
        defineField({
            name: "resetTokenExpires",
            title: "Срок действия токена сброса",
            type: "datetime",
            description: "Срок действия токена восстановления",
            group: "auth",
        }),
        defineField({
            name: "donations",
            title: "Пожертвования",
            type: "array",
            description: "Пожертвования пользователя",
            of: [{
                type: "object",
                name: "donation",
                fields: [
                    // {
                    //     name: "email",
                    //     title: "Email",
                    //     type: "string",
                    //     description: "Email пользователя",
                    // },
                    {
                        name: "orderNumber",
                        title: "Номер заказа",
                        type: "string",
                    },
                    {
                        name: "amount",
                        title: "Сумма пожертвования",
                        type: "number",
                        description: "Сумма пожертвования пользователя",
                    },
                    defineField({
                        name: "createdAt",
                        title: "Дата создания пожертвования",
                        type: "datetime",
                        description: "Дата создания пожертвования пользователя",
                        validation: (Rule) => Rule.required(),
                        initialValue: () => new Date().toISOString(),
                    }),
                ]
            }],
            group: "donations",
        }),
        defineField({
            name: "createdAt",
            title: "Дата создания",
            type: "datetime",
            description: "Дата создания аккаунта пользователя",
            validation: (Rule) => Rule.required(),
            initialValue: () => new Date().toISOString(),
            group: "meta",
        }),
    ],
    preview: {
        select: {
            title: "name",
            subtitle: "userId",
            description: "totalAmount",
        },
        prepare({ title, subtitle, description }) {
            return {
                title: title || "Без имени",
                subtitle: `ID: ${subtitle} | Сумма: ${description} RUB`,
            };
        },
    },
});